### ISSUE TITLE
Min Max

### ISSUE THREAD

**Issue by Pickleheaded** [tallneil/tweakpane-plugin-inputs#4]
HI, Not an issue but after setting the initial min/max values when creating the control, can the min/max values be changed after creation?

Something along the lines of PARAMS.stepper.min(newValue);

Many thanks

**Comment by tallneil** [comment]
Hi! A similar topic was answered in the main tweakpane repo:

https://github.com/cocopon/tweakpane/issues/390#issuecomment-1091038674

Lmk if this works for you! 

I'm curious - how did you come across this plugin? And what's your project / use case for it?

**Comment by Pickleheaded** [comment]
Thanks for the reply!!

Found it on github at https://tweakpane.github.io/docs/ and then plugins link at the bottom of page.

I'm helping a friend by creating a  three.js 3d staircase designer and hoping that by using tweakpane I can have a simplified menu code and with this plugin have greater control over dimension increments.

**Comment by tallneil** [comment]
Nice, good luck!

**Comment by Pickleheaded** [comment]
Hi, just an update, disposing of the input plugin and recreating the input with new min/max values works perfectly!
![Screenshot 2024-10-09 121547](https://github.com/user-attachments/assets/8c7cc37a-511a-4841-9a14-3e4dd38029b6)
